const lightColors = {
  primary: '#44A2D6',
  onPrimary: '#FFFFFF',
  primaryContainer: '#D6F1FF',
  onPrimaryContainer: '#00324B',
  secondary: '#0F766E',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#CCFBF1',
  onSecondaryContainer: '#134E4A',
  tertiary: '#7C3AED',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#EDE9FE',
  onTertiaryContainer: '#4C1D95',
  background: '#F9FAFB',
  onBackground: '#111827',
  surface: '#FFFFFF',
  onSurface: '#111827',
  surfaceVariant: '#F3F4F6',
  onSurfaceVariant: '#6B7280',
  inverseSurface: '#111827',
  inverseOnSurface: '#F9FAFB',
  inversePrimary: '#9ED9F2',
  error: '#EF4444',
  onError: '#FFFFFF',
  errorContainer: '#FEE2E2',
  onErrorContainer: '#7F1D1D',
  outline: '#E5E7EB',
  outlineVariant: '#F1F5F9',
  surfaceTint: '#44A2D6',
  scrim: 'rgba(0, 0, 0, 0.35)',
  shadow: 'rgba(0, 0, 0, 0.2)',
  onScrim: '#E5E7EB',
};

const darkColors = {
  primary: '#44A2D6',
  onPrimary: '#FFFFFF',
  primaryContainer: '#0B2B3B',
  onPrimaryContainer: '#BDEBFF',
  secondary: '#5EEAD4',
  onSecondary: '#0F172A',
  secondaryContainer: '#134E4A',
  onSecondaryContainer: '#CCFBF1',
  tertiary: '#C4B5FD',
  onTertiary: '#1F1147',
  tertiaryContainer: '#4C1D95',
  onTertiaryContainer: '#EDE9FE',
  background: '#0F172A',
  onBackground: '#F8FAFC',
  surface: '#1E293B',
  onSurface: '#F8FAFC',
  surfaceVariant: '#111827',
  onSurfaceVariant: '#94A3B8',
  inverseSurface: '#F8FAFC',
  inverseOnSurface: '#0F172A',
  inversePrimary: '#2D7BA6',
  error: '#F87171',
  onError: '#0F172A',
  errorContainer: '#7F1D1D',
  onErrorContainer: '#FEE2E2',
  outline: '#374151',
  outlineVariant: '#1F2937',
  surfaceTint: '#44A2D6',
  scrim: 'rgba(0, 0, 0, 0.6)',
  shadow: 'rgba(0, 0, 0, 0.6)',
  onScrim: '#CBD5E1',
};

const brand = {
  name: 'Finn',
  domain: 'finnsocial.fun',
  colors: {
    primary: lightColors.primary,
    secondary: lightColors.secondary,
    accent: lightColors.tertiary,
    background: lightColors.background,
    surface: lightColors.surface,
  },
};

module.exports = {
  lightColors,
  darkColors,
  brand,
};
