#!/usr/bin/env python3
import json
import os

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SOURCE_PATH = os.path.join(ROOT_DIR, "config", "permissions-info-plist.json")

SUPPORTED_LOCALES = ["en", "pt", "es", "fr", "de", "ja", "ar"]
REQUIRED_KEYS = ["NSCameraUsageDescription", "NSPhotoLibraryUsageDescription"]

if not os.path.exists(SOURCE_PATH):
    raise FileNotFoundError(f"[generate-info-plist-strings] Missing {SOURCE_PATH}")

with open(SOURCE_PATH, "r", encoding="utf-8") as handle:
    permission_strings = json.load(handle)

missing_locales = [locale for locale in SUPPORTED_LOCALES if locale not in permission_strings]
if missing_locales:
    raise ValueError(
        "[generate-info-plist-strings] Missing locales: " + ", ".join(missing_locales)
    )


def escape_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_plist_strings(entries: dict) -> str:
    header = "/* Generated by scripts/generate-info-plist-strings.py. */\n"
    lines = []
    for key in REQUIRED_KEYS:
        value = entries.get(key)
        if not value:
            raise ValueError(f"[generate-info-plist-strings] Missing key {key}")
        lines.append(f"\"{key}\" = \"{escape_value(value)}\";")
    return f"{header}{os.linesep.join(lines)}{os.linesep}"


for target in ["Finn", "FinnDev"]:
    for locale in SUPPORTED_LOCALES:
        lproj_dir = os.path.join(ROOT_DIR, "ios", target, f"{locale}.lproj")
        os.makedirs(lproj_dir, exist_ok=True)
        output_path = os.path.join(lproj_dir, "InfoPlist.strings")
        with open(output_path, "w", encoding="utf-8") as handle:
            handle.write(render_plist_strings(permission_strings[locale]))

print("[generate-info-plist-strings] Updated InfoPlist.strings files.")
