-- Core schema for Finn (Supabase)
-- Adjust columns/policies as product rules are finalized.

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  name text not null,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "Profiles are viewable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can insert own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id);

create table if not exists public.communities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.communities enable row level security;

create policy "Communities are viewable by authenticated users"
  on public.communities for select
  to authenticated
  using (true);

create policy "Users can create communities"
  on public.communities for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Owners can update communities"
  on public.communities for update
  to authenticated
  using (auth.uid() = owner_id);

create policy "Owners can delete communities"
  on public.communities for delete
  to authenticated
  using (auth.uid() = owner_id);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  content text not null,
  image_url text,
  community_id bigint not null references public.communities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

create policy "Posts are viewable by authenticated users"
  on public.posts for select
  to authenticated
  using (true);

create policy "Users can create posts"
  on public.posts for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own posts"
  on public.posts for update
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can delete own posts"
  on public.posts for delete
  to authenticated
  using (auth.uid() = user_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  content text not null,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

create policy "Comments are viewable by authenticated users"
  on public.comments for select
  to authenticated
  using (true);

create policy "Users can create comments"
  on public.comments for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can delete own comments"
  on public.comments for delete
  to authenticated
  using (auth.uid() = user_id);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

alter table public.likes enable row level security;

create policy "Likes are viewable by authenticated users"
  on public.likes for select
  to authenticated
  using (true);

create policy "Users can like posts"
  on public.likes for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can remove own likes"
  on public.likes for delete
  to authenticated
  using (auth.uid() = user_id);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (community_id, user_id)
);

alter table public.subscriptions enable row level security;

create policy "Subscriptions are viewable by authenticated users"
  on public.subscriptions for select
  to authenticated
  using (true);

create policy "Users can subscribe"
  on public.subscriptions for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can unsubscribe"
  on public.subscriptions for delete
  to authenticated
  using (auth.uid() = user_id);

create index if not exists posts_by_community on public.posts (community_id, created_at desc);
create index if not exists posts_by_user on public.posts (user_id, created_at desc);
create index if not exists comments_by_post on public.comments (post_id, created_at);
create index if not exists likes_by_post on public.likes (post_id);
create index if not exists subscriptions_by_user on public.subscriptions (user_id);
