-- Saved posts (bookmarks)

create table if not exists public.saved_posts (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

alter table public.saved_posts enable row level security;

create policy "Saved posts are viewable by owner"
  on public.saved_posts for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can save posts"
  on public.saved_posts for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can remove saved posts"
  on public.saved_posts for delete
  to authenticated
  using (auth.uid() = user_id);

create index if not exists saved_posts_by_user on public.saved_posts (user_id, created_at desc);
