-- Push notification tokens

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  token text not null,
  platform text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists push_tokens_unique on public.push_tokens (token);
create index if not exists push_tokens_user on public.push_tokens (user_id);

alter table public.push_tokens enable row level security;

create policy "Push tokens are viewable by owner"
  on public.push_tokens for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own push tokens"
  on public.push_tokens for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own push tokens"
  on public.push_tokens for update
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can delete own push tokens"
  on public.push_tokens for delete
  to authenticated
  using (auth.uid() = user_id);
