-- Notifications + follows

create table if not exists public.user_follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, following_id),
  constraint user_follows_no_self_follow check (follower_id <> following_id)
);

alter table public.user_follows enable row level security;

create policy "User follows are viewable by authenticated users"
  on public.user_follows for select
  to authenticated
  using (true);

create policy "Users can follow others"
  on public.user_follows for insert
  to authenticated
  with check (auth.uid() = follower_id);

create policy "Users can unfollow"
  on public.user_follows for delete
  to authenticated
  using (auth.uid() = follower_id);

create index if not exists user_follows_by_follower on public.user_follows (follower_id, created_at desc);
create index if not exists user_follows_by_following on public.user_follows (following_id, created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('follow', 'post_like', 'post_comment')),
  post_id bigint references public.posts(id) on delete cascade,
  metadata jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.notifications enable row level security;

create policy "Notifications are viewable by recipient"
  on public.notifications for select
  to authenticated
  using (auth.uid() = recipient_id);

create policy "Recipients can update read status"
  on public.notifications for update
  to authenticated
  using (auth.uid() = recipient_id);

create index if not exists notifications_by_recipient on public.notifications (recipient_id, created_at desc);
create index if not exists notifications_by_recipient_unread on public.notifications (recipient_id, read_at);

create or replace function public.create_follow_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient uuid;
begin
  recipient := new.following_id;

  if recipient is null or recipient = new.follower_id then
    return new;
  end if;

  insert into public.notifications (recipient_id, actor_id, type)
  values (recipient, new.follower_id, 'follow');

  return new;
end;
$$;

create or replace function public.create_like_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient uuid;
begin
  select user_id into recipient from public.posts where id = new.post_id;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  insert into public.notifications (recipient_id, actor_id, type, post_id)
  values (recipient, new.user_id, 'post_like', new.post_id);

  return new;
end;
$$;

create or replace function public.create_comment_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient uuid;
  preview text;
begin
  select user_id into recipient from public.posts where id = new.post_id;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  preview := left(new.content, 140);

  insert into public.notifications (recipient_id, actor_id, type, post_id, metadata)
  values (recipient, new.user_id, 'post_comment', new.post_id, jsonb_build_object('comment_preview', preview));

  return new;
end;
$$;

drop trigger if exists trg_notify_follow on public.user_follows;
create trigger trg_notify_follow
  after insert on public.user_follows
  for each row execute function public.create_follow_notification();

drop trigger if exists trg_notify_like on public.likes;
create trigger trg_notify_like
  after insert on public.likes
  for each row execute function public.create_like_notification();

drop trigger if exists trg_notify_comment on public.comments;
create trigger trg_notify_comment
  after insert on public.comments
  for each row execute function public.create_comment_notification();
