name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: KtLint
        run: ./gradlew ktlintCheck
      - name: Detekt
        run: ./gradlew detekt
      - name: Android Lint
        run: ./gradlew :app:lintDebug
      - name: Assemble
        run: ./gradlew :app:assembleDebug
